### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by clrxbl**

### CODE REVIEW

**Comment by stephlocke** [comment]
Fab - thanks @clrxbl!

Some tips for your next PRs:

- Reference the issue if you're solving something specific. You can do this by putting the issue number in the title e.g. #1 
- If someone requests changes, you can keep amending your existing copy of the code and the PR will get updated so all your changes are incorporated

Thank you for the submission and happy #hacktoberfest!

**Comment by clrxbl** [comment]
Thanks for the information!

**Comment by stephlocke** [comment]
Oops - almost forgot! 
If you'd like a Locke Data sticker - fill in this form and we'll send one out to you at the end of the month 👊 https://airtable.com/tblYkXKrZmIVIxrqD/viwMGHvEelDC0d1kz

**Comment by clrxbl** [comment]
Don't seem to have access, requested access.

**Comment by stephlocke** [comment]
Oops - I'm on a roll 🤦‍♀️
https://airtable.com/shr31Z5XIyGbbwqFb

**Comment by clrxbl** [comment]
How do these stickers even look like?

**Comment by stephlocke** [comment]
image

**Pull request merged**
